import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./styles/top-bar.css";
import Script from "next/script";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="bg">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Топ бар (HTML + твоя JS/CSS) */}
        <div className="top-bar">
          <div className="top-bar-content">
            <a href="https://dmphysi0.com" aria-label="Начало" className="flex items-center gap-2">
              <Image
                src="/logo.png"
                alt="ДМ Физио Лого"
                width={50}
                height={50}
                className="main-logo"
                priority
              />
            </a>

            <button className="hamburger-menu-toggle" aria-label="Toggle navigation">
              <span style={{ fontSize: 28, lineHeight: 1 }}>☰</span>
            </button>

            <nav className="main-nav">
              <ul>
                <li><a href="https://dmphysi0.com">Начало</a></li>

                <li className="dropdown">
                  <a href="https://dmphysi0.com/services.html" className="dropbtn">Процедури и Цени</a>
                  <div className="dropdown-content">
                    <a href="https://dmphysi0.com/kinesitherapy.html">Кинезитерапия</a>
                    <a href="https://dmphysi0.com/massages.html">Масажи</a>
                    <a href="https://dmphysi0.com/online-recovery.html">Онлайн Процедури</a>
                  </div>
                </li>

                <li><a href="https://dmphysi0.com/pain-conditions.html">Болкови състояния</a></li>
                <li><a href="https://dmphysi0.com/shop.html">Онлайн Магазин</a></li>
                <li><a href="https://dmphysi0.com/contact.html">Контакти</a></li>
              </ul>
            </nav>
          </div>
        </div>

        {/* Отместване надолу, защото топ барът е fixed */}
        <div style={{ height: 64 }} />

        {children}

        {/* Твоят legacy JS от public/ */}
        <Script src="/topbar.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}
