// app/layout.tsx
import type { Metadata } from "next";
import Image from "next/image";
import "./globals.css";
import "./styles/top-bar.css";
import Script from "next/script";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="bg">
      <body className="antialiased">
        {/* Топ бар */}
        <header className="tb-header">
          <div className="tb-inner">
            <a href="https://dmphysi0.com" aria-label="Начало">
              <Image
                src="/logo.png"
                alt="ДМ Физио Лого"
                width={60}
                height={60}
                className="tb-logo"
                priority
              />
            </a>

            <nav className="tb-nav" id="tbNav">
              <ul className="tb-menu">
                <li className="tb-item">
                  <a className="tb-link" href="https://dmphysi0.com">Начало</a>
                </li>

                <li className="tb-item tb-dropdown">
                  <a
                    className="tb-link tb-drop-toggle"
                    data-dropdown="toggle"
                    href="https://dmphysi0.com/services.html"
                  >
                    Процедури и Цени
                  </a>
                  <div className="tb-drop-menu">
                    <a className="tb-drop-link" href="https://dmphysi0.com/kinesitherapy.html">Кинезитерапия</a>
                    <a className="tb-drop-link" href="https://dmphysi0.com/massages.html">Масажи</a>
                    <a className="tb-drop-link" href="https://dmphysi0.com/online-recovery.html">Онлайн Процедури</a>
                  </div>
                </li>

                <li className="tb-item">
                  <a className="tb-link" href="https://dmphysi0.com/pain-conditions.html">Болкови състояния</a>
                </li>
                <li className="tb-item">
                  <a className="tb-link" href="https://dmphysi0.com/shop.html">Онлайн Магазин</a>
                </li>
                <li className="tb-item">
                  <a className="tb-link" href="https://dmphysi0.com/contact.html">Контакти</a>
                </li>
              </ul>
            </nav>

            <button className="tb-burger" id="tbBurger" aria-label="Отвори меню" aria-expanded="false">
              ☰
            </button>
          </div>
        </header>

        {/* Отместване под фиксирания бар */}
        <div className="tb-push" />

        {children}

        {/* legacy JS */}
        <Script src="/topbar.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}
